2 October 2023

## `NumPy`

In [1]:
import numpy as np

- one of the core packages for numerical computing in Python
- many packages built on `numpy`
- has been optimized for processing


### Variables

In [3]:
# assigning a small array to variable "a"

a = np.array([[1,1,2], [3,5,8]])

We can see that variable value in two ways:

In [4]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
print(a)

[[1 1 2]
 [3 5 8]]


### Naming Variables

We are going to most often use `snake_case` for naming variables

**object**: bundle of properties and actions about something 
- e.g. object: df, properties: # of rows, names of colums, data created
    - actions: selecting a row, adding a column
- Sun: object
    - soleil is French for sun, sol is Spanish for sun
- in practice we will use object and variable interchangably

**type**: what kind of object, can also be called the **class**
- can see the type by using the `type()` function

In [ ]:
type(a)

numpy.ndarray

The `numpy.ndarray` is the core data type in the `NumPy` package.

Check type of an entry by indexing:

In [8]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

*How would you access the value 5 in array a?*

In [11]:
print(a)
print(a[1,1]) #second row, second column

[[1 1 2]
 [3 5 8]]
5


### Functions

`print` is a Python function

**function**: takes in a set of arguments and uses them to produce an output

argument = parameter

We can ask info about a funciton by using `?function_name`

In [12]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


##### Different types of arguments

**non-optional arguments**: arguments you need to specify for the function to work

**optional arguments**: arguments pre-filled with a default value that can be overridden.

In [13]:
print(a, end = ':)')

[[1 1 2]
 [3 5 8]]:)

### Attributes and Methods

An object in Python has attrubites and methods.

**attribute**: a property of an object, a piece of information about it
- weight, color, species

**method**: a procedure associated with an object, an action where main parameter is an object
- swim(), eat(), jump()

Access a variable's attributes and methods by adding a `.` at the end of the variable name

- `variable.variable_method()`

- `variable.variable_attribute`

Examples:

In [2]:
#define a 3x3 array

var = np.array( [ [1,2,3], [4,5,6], [7,8,9] ] )
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#shape: attribute telling us # of elements in each dim. of array

var.shape

(3, 3)

In [12]:
var.ndim

2

In [13]:
type(var.ndim)

int

Examples of **methods**:

In [15]:
#return minimum value of the array
var.min()

1

In [17]:
type(var.min)

builtin_function_or_method

#### R and Python

R: does not use methods within an object
- functions are extrinstic (outside) the objects they are acting on

Example:

In R there are two seperate items' `var` and function `min`

```
# R code
var <- array(c(1,4,7,2,5,8,3,6,9), dim = c(3,3))

min(var)
```

Using the pipe operator `%>%`, this is closer to the `.` in Python

```
var <- array(c(1,4,7,2,5,8,3,6,9), dim = c(3,3))

var %>% 
    min()
```

The pipe `%>%` is passing `var` to the `min()` funtion as it's first argument. This is what the `.` does in Python.

```
var.min()
```